---
title: "Selected Papers"
---

##### Bayesian estimation of COVID-19 excess deaths over multiple years
Bryant J., Dunstan K., Senanayake P.,  Varn L., Zhang J. 2026. **Estimating COVID-19 excess mortality during and after the pandemic: A Bayesian model, with an application to New Zealand**. *Demographic Research* 55(17): 491-532

<https://doi.org/10.4054/DemRes.2026.55.17>{target="_blank" rel="noopener noreferrer"}

---

##### Subnational population estimation in England and Wales
Dynamic Population Model Project Team. 2023. **Design and Implementation of the Dynamic Population Model: Version 2.0**

<https://uksa.statisticsauthority.gov.uk/wp-content/uploads/2023/02/EAP193-DPM-progress-report-and-technical-paper.pdf>{target="_blank" rel="noopener noreferrer"}

---

##### Modelling and forecasting childhood obesity using admin data
Bryant, J., Rittirong, J., Aekplakorn, W., Mo-suwan, L., & Nitnara, P. 2022. **A Bayesian approach to combining multiple information sources: Estimating and forecasting childhood obesity in Thailand.** *PLOS ONE*.

<https://doi.org/10.1371/journal.pone.0262047>{target="_blank" rel="noopener noreferrer"}

---

##### Estimating obesity rates for small groups
Rittirong, J., Bryant, J., Aekplakorn, W., Prohmmo, A., & Sunpuwan, M. 2021. **Obesity and occupation in Thailand: using a Bayesian hierarchical model to obtain prevalence estimates from the National Health Examination Survey.** *BMC Public Health*, 21, 914.

<https://doi.org/10.1186/s12889-021-10944-0>{target="_blank" rel="noopener noreferrer"}

---

##### Forecasting migration with small counts
Zhang, J., & Bryant, J. 2020. **Bayesian disaggregated forecasts: Internal migration in Iceland.** In S. Mazzuco & N. Keilman (Eds.), *Developments in Demographic Forecasting*. Springer.

<https://doi.org/10.1007/978-3-030-42472-5_10>{target="_blank" rel="noopener noreferrer"}

---

##### Bayesian benchmarking of small area estimates
Zhang, J., & Bryant, J. 2020. **Fully Bayesian benchmarking of small area estimation models.** *Journal of Official Statistics*, 36(1), 197–223.

<https://doi.org/10.2478/jos-2020-0010>{target="_blank" rel="noopener noreferrer"}

---

##### Combining multiple imperfect data sources for small area estimation
Zhang, J., & Bryant, J. 2019. **Combining multiple imperfect data sources for small area estimation: a Bayesian model of provincial fertility rates in Cambodia.** *Statistical Theory and Related Fields*, 3(2), 178–185.

<https://doi.org/10.1080/24754269.2019.1658062>{target="_blank" rel="noopener noreferrer"}

---

##### Introduction to Bayesian demography
Bijak, J., & Bryant, J. 2019. **Bayesian demography.** *Statistics Reference Online*. John Wiley & Sons, Ltd.

<https://doi.org/10.1002/9781118445112.stat07838>{target="_blank" rel="noopener noreferrer"}

---

##### Bayesian small area demography
Zhang, J., Bryant, J., & Nissen, K. 2019. **Bayesian small area demography.** *Survey Methodology*, 45(1).

<https://www150.statcan.gc.ca/n1/pub/12-001-x/2019001/article/00001-eng.pdf>{target="_blank" rel="noopener noreferrer"}

---

##### Bayesian forecasting of demographic rates for small areas
Bryant, J., & Zhang, J. 2016. **Bayesian forecasting of demographic rates for small areas: Emigration rates by age, sex, and region in New Zealand, 2014–2038.** *Statistica Sinica*, 26, 1337–1363.

<https://doi.org/10.5705/ss.2014.200t>{target="_blank" rel="noopener noreferrer"}

---

##### Overview of Bayesian demography
Bijak, J., & Bryant, J. 2016. **Bayesian demography 250 years after Bayes.** *Population Studies*, 70(1), 1–19.

<https://doi.org/10.1080/00324728.2015.1122826>{target="_blank" rel="noopener noreferrer"}

---

##### Probabilistic forecasts for informed decision making
Bijak, J., Alberts, I., Alho, J., Bryant, J., Buettner, T., Falkingham, J., Forster, J., Gerland, P., King, T., Onorante, L., Keilman, N., O’Hagan, A., Owens, D., Raftery, A., Ševčíková, H., & Smith, P. 2016.  **Letter to the Editor: Probabilistic population forecasts for informed decision making.** *Journal of Official Statistics*, 31(4), 537–544.

<https://doi.org/10.1515/jos-2015-0035>{target="_blank" rel="noopener noreferrer"}

---

##### A Bayesian approach to population estimation
Bryant, J., & Graham, P. 2015. **A Bayesian approach to population estimation with administrative data.** *Journal of Official Statistics*, 31(3).

<https://doi.org/10.1515/jos-2015-0028>{target="_blank" rel="noopener noreferrer"}


##### Bayesian demographic accounts
Bryant, J., & Graham, P. 2013. **Bayesian demographic accounts: Subnational population estimation using multiple data sources**. *Bayesian Analysis*. 8(3): 591--622.

<https://doi.org/10.1214/13-BA820>{target="_blank" rel="noopener noreferrer"}
